# fly.toml app configuration file generated for tc-agi-backend-exrd1g on 2025-10-17T17:00:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tc-agi-backend-exrd1g'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
